name: CI for E2E Screenshot Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd e2e-screenshot-tests
        npm install

    - name: Run e2e tests
      run: |
        cd e2e-screenshot-tests
        npx playwright install # Це встановить необхідні браузери для Playwright
        npm test
