name: CI for E2E Screenshot Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd e2e-screenshot-tests
        npm install

    - name: Install Playwright browsers
      run: |
        cd e2e-screenshot-tests
        npx playwright install --with-deps  # Встановлення браузерів та залежностей для Playwright

    - name: Verify Playwright installation
      run: |
        cd e2e-screenshot-tests
        ls -l ./node_modules/.bin/playwright  # Перевіряємо наявність файлу та його права доступу

    - name: Grant execute permissions for Playwright
      run: |
        cd e2e-screenshot-tests
        chmod +x ./node_modules/.bin/playwright || true  # Додаємо права на виконання, якщо вони відсутні

    - name: Run e2e tests
      run: |
        cd e2e-screenshot-tests
        npx playwright test
