name: Lab CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies and Playwright
      working-directory: ./e2e-screenshot-tests  # Вказуємо правильний каталог з package.json
      run: |
        npm install
        npx playwright install --with-deps  # Встановлення Playwright з усіма системними залежностями

    - name: Ensure permissions for Playwright
      working-directory: ./e2e-screenshot-tests  # Тут також вказуємо правильний каталог
      run: chmod +x node_modules/.bin/playwright

    - name: Run tests
      working-directory: ./e2e-screenshot-tests/tests  # Шлях до тестових файлів
      run: npm test





