name: CI for E2E Screenshot Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Set permissions for Playwright
      run: chmod +x ./node_modules/.bin/playwright

    - name: Run e2e tests
      run: cd e2e-screenshot-tests && npm test

