name: CI for E2E Screenshot Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd e2e-screenshot-tests
        npm install

    - name: Install Playwright browsers
      run: |
        cd e2e-screenshot-tests
        npx playwright install

    - name: Verify Playwright installation
      run: |
        cd e2e-screenshot-tests
        ls -l ./node_modules/.bin/playwright  # Перевіримо наявність файлу та його права доступу

    - name: Fix Playwright permissions
      run: |
        cd e2e-screenshot-tests
        chmod +x ./node_modules/.bin/playwright  # Додамо дозволи на виконання для файлу

    - name: Run e2e tests
      run: |
        cd e2e-screenshot-tests
        npm test
